version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 739275462844.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t gandhi-final-exam .
      - docker tag gandhi-final-exam:latest 739275462844.dkr.ecr.us-east-1.amazonaws.com/gandhi-final-exam:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 739275462844.dkr.ecr.us-east-1.amazonaws.com/gandhi-final-exam:latest
      - printf '[{"name":"gandhi-final-exam-container","imageUri":"%s"}]' 739275462844.dkr.ecr.us-east-1.amazonaws.com/gandhi-final-exam:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json